name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          # Remove unnecessary or incorrect inputs
          # build-tools: 30.0.3
          # sdk-version: '30.0.3'

      - name: Accept Android SDK Licenses
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android Platform Tools
        run: $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager platform-tools

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Update to node20 or later to avoid deprecation warning

      - name: Install dependencies
        run: npm install

      - name: Build the Android app
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
